/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = {
  "productData": {
    "jackets": [
      {
        "values": [
          "Check out this Navy Blue Roadies By Justanned handcrafted real leather sleeves and nylon body combined jacket, is designed in a typical racer silhouette with ribbed collar, cuffs and hem. It's cut from soft leather with a detail ROADIES ADVENTURE PRINT on front. Also it comes with snap fastening closure and nylon long lasting durability. ",
          "RJM-215-4",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting s",
          "Yes",
          "1",
          "Gun Metal",
          "Polyester",
          "Nylon+Lamb leather",
          "2",
          "Bomber",
          "Clean By Leather Specialist",
          "Jackets",
          "RJM-215-4",
          "Full Sleeves",
          "Casual",
          "Rib Collar",
          "Adult",
          "Regular Fit",
          "Fashion",
          "Navy Blue"
        ],
        "discount": 75,
        "category2": "jackets",
        "category3": "bomber",
        "category1": "men",
        "inStock": true,
        "title": "ROADIES BY JUSTANNED NAVY BLUE RIBBED MEN'S BOMBER JACKET",
        "stock": 70,
        "product_code": "SKU:RJM-215-4",
        "discounted_price": 1750,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "NEW IN",
          "Inner Pocket",
          "Zipper Info",
          "Lining Material",
          "Material/Fabric",
          "Front Pocket",
          "Concept",
          "Material Care",
          "Type",
          "Style Code",
          "Sleeve Length",
          "Occasion",
          "Neck Type",
          "Age Group",
          "Fit Type",
          "Fashion Type",
          "Color"
        ],
        "price": 7000,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_2_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_3_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_4_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_5_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/r/j/rjm-215-4_6_1.jpg"
        ],
        "description": "Check out this Navy Blue Roadies By Justanned handcrafted real leather sleeves and nylon body combined jacket, is designed in a typical racer silhouette with ribbed collar, cuffs and hem. It's cut from soft leather with a detail ROADIES ADVENTURE PRINT on front. Also it comes with snap fastening closure and nylon long lasting durability. "
      },
      {
        "price": 20000,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13-1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_2_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_3_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_4_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_5_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_6_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtjm142-13_7_1.jpg"
        ],
        "description": "Add a touch of definition to an otherwise solid look with this treated beige coloured leather jacket from the house of Justanned. A wear-anywhere piece, created using leather, just to add a dash of attraction to your overall look. Meant to last a lifetime, this piece will make you look smart no matter what you wear it with. ",
        "values": [
          "Add a touch of definition to an otherwise solid look with this treated beige coloured leather jacket from the house of Justanned. A wear-anywhere piece, created using leather, just to add a dash of attraction to your overall look. Meant to last a lifetime, this piece will make you look smart no matter what you wear it with.",
          " JTJM142-13",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "2",
          "Black Matte",
          "Polyester",
          "Leather",
          "4",
          "Casual",
          "Clean By Leather Specialist",
          "Jackets",
          " JTJM142-13",
          "Full Sleeves",
          "Casual",
          "7",
          "Band Collar",
          "Adult",
          "Zipper",
          "Regular Fit",
          "Fashion",
          "Beige"
        ],
        "discount": 75,
        "category2": "jackets",
        "category3": "biker",
        "category1": "men",
        "inStock": true,
        "title": "JUSTANNED TREATED BEIGE LEATHER JACKET",
        "stock": 83,
        "product_code": "SKU: JTJM142-13",
        "discounted_price": 5000,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Inner Pocket",
          "Zipper Info",
          "Lining Material",
          "Material/Fabric",
          "Front Pocket",
          "Concept",
          "Material Care",
          "Type",
          "Style Code",
          "Sleeve Length",
          "Occasion",
          "No. of Zip",
          "Neck Type",
          "Age Group",
          "Closure",
          "Fit Type",
          "Fashion Type",
          "Color"
        ]
      },
      {
        "category3": "casual",
        "category1": "men",
        "inStock": true,
        "title": "GUY LAROCHE MEN'S VERTICAL FRONT ZIP LEATHER JACKET",
        "stock": 97,
        "product_code": "SKU:GLJ-060-4",
        "discounted_price": 4499,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "NEW IN",
          "Inner Pocket",
          "Zipper Info",
          "Lining Material",
          "Material/Fabric",
          "Front Pocket",
          "Concept",
          "Material Care",
          "Year",
          "No. of Pockets",
          "Type",
          "Style Code",
          "Sleeve Length",
          "Occasion",
          "No. of Zip",
          "Neck Type",
          "Age Group",
          "Closure",
          "Fit Type",
          "Length",
          "Fashion Type",
          "Color"
        ],
        "price": 14998,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_7.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-060-4_1.jpg"
        ],
        "description": "Bring out the style icon in you by wearing this jacket from Guy Laroche. It has been made of a premium quality leather that lends it a refined finish. It also comes with a front vertical zipped pocket, which ensures convenience while wearing it. Besides, ",
        "values": [
          "Bring out the style icon in you by wearing this jacket from Guy Laroche. It has been made of a premium quality leather that lends it a refined finish. It also comes with a front vertical zipped pocket, which ensures convenience while wearing it. Besides, ",
          "GLJ-060-4",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting s",
          "Yes",
          "2",
          "Gun Metal",
          "Cotton",
          "Lamb Leather",
          "4",
          "Casual",
          "Clean By Leather Specialist",
          "2019",
          "6",
          "Jackets",
          "GLJ-060-4",
          "Long Sleeves",
          "Casual",
          "6",
          "Shirt Collar",
          "Adult",
          "Zipper",
          "Regular Fit",
          "Full Length",
          "Fashion",
          "Blue"
        ],
        "discount": 70,
        "category2": "jackets"
      },
      {
        "discounted_price": 6600,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "NEW IN",
          "Inner Pocket",
          "Lining Material",
          "Material/Fabric",
          "Front Pocket",
          "Concept",
          "Material Care",
          "Year",
          "No. of Pockets",
          "Type",
          "Style Code",
          "Sleeve Length",
          "Occasion",
          "No. of Zip",
          "Neck Type",
          "Age Group",
          "Closure",
          "Fit Type",
          "Length",
          "Fashion Type",
          "Color"
        ],
        "price": 21999,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/g/l/glj-052-23_7.jpg"
        ],
        "description": "Welcome the winters with this superlative saddle jacket from the latest collection of Guy Laroche. Tailored in a regular fit to comfortably accommodate layering, the premium leather construction is designed to keep you warm and cosy in the chill. Pair it ",
        "values": [
          "Welcome the winters with this superlative saddle jacket from the latest collection of Guy Laroche. Tailored in a regular fit to comfortably accommodate layering, the premium leather construction is designed to keep you warm and cosy in the chill. Pair it ",
          "GLJ-052-23",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting s",
          "Yes",
          "2",
          "Polyester",
          "Lamb Leather",
          "6",
          "Formal",
          "Clean By Leather Specialist",
          "2019",
          "8",
          "Jackets",
          "GLJ-052-23",
          "Long Sleeves",
          "Casual",
          "1",
          "Shirt Collar",
          "Adult",
          "Zipper",
          "Comfort Fit",
          "Full Length",
          "Fashion",
          "Saddle"
        ],
        "discount": 70,
        "category2": "jackets",
        "category3": "formal",
        "category1": "men",
        "inStock": true,
        "title": "GUY LAROCHE MEN'S SADDLE TAILORED LEATHER JACKET",
        "stock": 24,
        "product_code": "SKU:GLJ-052-23"
      }
    ],
    "wallets": [
      {
        "description": "Keep your essentials close at hand with this stylish wristlet wallet. Crafted from genuine leather, the wallet features stylish gold-finished accents for a sophisticated addition to any outfit. ",
        "values": [
          "Keep your essentials close at hand with this stylish wristlet wallet. Crafted from genuine leather, the wallet features stylish gold-finished accents for a sophisticated addition to any outfit. ",
          "JTWW235-12",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "WOMEN'S WALLET",
          "Bovine Leather",
          "0",
          "Cotton",
          "2",
          "Wallets",
          "JTWW235-12",
          "Standard",
          "Casual",
          "1",
          "2",
          "Adult",
          "Zipper",
          "Fashion",
          "Orange",
          "20.32",
          "8",
          "13.335",
          "5.25",
          "2.54",
          "1"
        ],
        "discount": 75,
        "category2": "wallets",
        "category3": "zip-wallet",
        "category1": "women",
        "inStock": true,
        "title": "JUSTANNED WOMEN ORANGE LEATHER WALLET WITH WRISTLET",
        "stock": 86,
        "productId": "14GfyBPSBJFosLD8gN9r",
        "product_code": "SKU:JTWW235-12",
        "discounted_price": 708,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Concept",
          "Material/Fabric",
          "No. of Compartments",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Card Slots",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Width (In)",
          "Height (CM)",
          "Height (In)",
          "Depth (CM)",
          "Depth (In)"
        ],
        "price": 2830,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-3_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww235-12-7.jpg"
        ]
      },
      {
        "category3": "zip-wallet",
        "category1": "women",
        "inStock": true,
        "title": "JUSTANNED TRIPPLE COMPARTMENT BLACK WALLET",
        "stock": 30,
        "productId": "1NnId9lKzP9g6rLSux0H",
        "product_code": "SKU:JTWW230-1",
        "discounted_price": 444,
        "labels": [
          "Item Description",
          "SKU",
          "NEW IN",
          "Material/Fabric",
          "No. of Compartments",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Card Slots",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Length (In)",
          "Width (CM)",
          "Width (In)",
          "Height (CM)",
          "Height (In)"
        ],
        "price": 1775,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1-1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww230-1_6.jpg"
        ],
        "description": "Here comes the bold and black Justanned leather wallet for women. It will keep your essentials handy as it's designed with unique pockets and stitching details on front. Follow the trend and carry Justanned. ",
        "values": [
          "Here comes the bold and black Justanned leather wallet for women. It will keep your essentials handy as it's designed with unique pockets and stitching details on front. Follow the trend and carry Justanned.",
          "JTWW230-1",
          "Yes",
          "Sheep",
          "3",
          "Polyester",
          "3",
          "Wallets",
          "JTWW230-1",
          "Standard",
          "Casual",
          "4",
          "2",
          "Adult",
          "Zipper",
          "Fashion",
          "Black",
          "6.5",
          "16.51",
          "6.5",
          "10.16",
          "4"
        ],
        "discount": 75,
        "category2": "wallets"
      },
      {
        "category3": "clutch",
        "category1": "women",
        "inStock": true,
        "title": "BEIGE PALM HELD WOMEN LEATHER WALLET",
        "stock": 41,
        "productId": "1wNkn1m6H5Y4sEjXD7Up",
        "product_code": "SKU:JTWW202-13",
        "discounted_price": 490,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Material/Fabric",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Zipper Info",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Card Slots",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ],
        "price": 1960,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww202-13.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWW202-13_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWW202-13_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWW202-13_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWW202-13_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWW202-13_6.jpg"
        ],
        "description": "Justanned sheep leather compact is a cute on the go wallet. Its small enough to fit in most pants pocket or your palm. The genuine sheep leather used to handcraft this wallet will get softer and richer over time. This wallet features a deep zipper pouch that can handle a large amount of coins. ",
        "values": [
          "Justanned sheep leather compact is a cute on the go wallet. Its small enough to fit in most pants pocket or your palm. The genuine sheep leather used to handcraft this wallet will get softer and richer over time. This wallet features a deep zipper pouch that can handle a large amount of coins.",
          "JTWW202-13",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Sheep Leather",
          "Cotton",
          "4",
          "Wallets",
          "Nickel",
          "JTWW202-13",
          "Standard",
          "Casual",
          "3",
          "Adult",
          "Zipper",
          "Fashion",
          "Beige",
          "2",
          "11"
        ],
        "discount": 75,
        "category2": "wallets"
      },
      {
        "values": [
          "Leather could be a style statement for your wardrobe. Check this Justanned women's leather wallet from the latest collection of zipped styles, as we have tried to provide you the utility and style with the fashionable spirit. ",
          "JTWW228-3",
          "Sheep",
          "3",
          "Polyester",
          "3",
          "Wallets",
          "JTWW228-3",
          "Standard",
          "Casual",
          "4",
          "2",
          "Adult",
          "Zipper",
          "Fashion",
          "Tan",
          "6.5",
          "16.51",
          "6.5",
          "10.16",
          "4"
        ],
        "discount": 75,
        "category2": "wallets",
        "category3": "zip-wallet",
        "category1": "women",
        "inStock": true,
        "title": "JUSTANNED TRIPPLE COMPARTMENT TAN WALLET",
        "stock": 5,
        "productId": "4Kds4tIT4WEZTTkiVKT7",
        "product_code": "SKU:JTWW228-3",
        "discounted_price": 444,
        "labels": [
          "Item Description",
          "SKU",
          "Material/Fabric",
          "No. of Compartments",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Card Slots",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Length (In)",
          "Width (CM)",
          "Width (In)",
          "Height (CM)",
          "Height (In)"
        ],
        "price": 1775,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3-1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtww228-3_6.jpg"
        ],
        "description": "Leather could be a style statement for your wardrobe. Check this Justanned women's leather wallet from the latest collection of zipped styles, as we have tried to provide you the utility and style with the fashionable spirit. "
      }
    ],
    "bags": [
      {
        "discounted_price": 1471,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Bags Type",
          "Material/Fabric",
          "Material Care",
          "No. of Compartments",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Zipper Info",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ],
        "price": 5882,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtwb616-2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTWB616-2_7.jpg"
        ],
        "description": "Get a fresh perspective on cool handbag decorum with this sophisticated yet street-chic crossbody from Justanned. The compact design is great for carrying all of your necessities as it looks incredible paired with your wardrobe. The bag is available in a variety of colors to match your style. ",
        "values": [
          "Get a fresh perspective on cool handbag decorum with this sophisticated yet street-chic crossbody from Justanned. The compact design is great for carrying all of your necessities as it looks incredible paired with your wardrobe. The bag is available in a variety of colors to match your style.",
          "JTWB616-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Sling Bag",
          "Leather",
          "Dry Clean By Leather Specialist",
          "1",
          "Polyester",
          "2",
          "Bags",
          "Pale Gold",
          "JTWB616-2",
          "Standard",
          "Casual",
          "3",
          "Adult",
          "Zipper",
          "Fashion",
          "Brown",
          "3.81",
          "17.78"
        ],
        "discount": 75,
        "category2": "bags",
        "category3": "crossbody",
        "category1": "women",
        "inStock": true,
        "title": "BROWN FRONT POCKET CROSSBODY BAG",
        "stock": 69,
        "productId": "0Ai91qKkL9mjHQl1e8WV",
        "product_code": "SKU:JTWB616-2"
      },
      {
        "category3": "sling-bags",
        "category1": "men",
        "inStock": true,
        "title": "JUSTANNED MEN'S BROWN LEATHER SLING BAG",
        "stock": 11,
        "productId": "0PEjLjAYnpP226l3tYUC",
        "product_code": "SKU:JTMB452-2",
        "discounted_price": 1803,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Bags Type",
          "Concept",
          "Material/Fabric",
          "Material Care",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Zipper Info",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Width (In)",
          "Height (CM)",
          "Height (In)"
        ],
        "price": 7210,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb452-2_7.jpg"
        ],
        "description": "Broaden the collection of your accessories in a trendy way with this men's sling bag from Justanned. This brown sling bag is high in quality and durability, courtesy to its premium quality leather and cotton inner material. It features an adjustable strap for easy carry and zipper closure for the safety of your valuables. You can store all your essentials in it. ",
        "values": [
          "Broaden the collection of your accessories in a trendy way with this men's sling bag from Justanned. This brown sling bag is high in quality and durability, courtesy to its premium quality leather and cotton inner material. It features an adjustable strap for easy carry and zipper closure for the safety of your valuables. You can store all your essentials in it.",
          "JTMB452-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Sling Bag",
          "SLING BAGS",
          "Goat Leather",
          "Dry Clean By Leather Specialist",
          "Polyester",
          "4",
          "Bags",
          "Gun Metal",
          "JTMB452-2",
          "Standard",
          "Formal",
          "3",
          "Adult",
          "ZIP CLOSURE",
          "Fashion",
          "Brown",
          "19.05",
          "7.5",
          "22.86",
          "9"
        ],
        "discount": 75,
        "category2": "bags"
      },
      {
        "product_code": "SKU:JTMB341-2",
        "discounted_price": 4140,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Bags Type",
          "Material/Fabric",
          "Material Care",
          "No. of Compartments",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Zipper Info",
          "Style Code",
          "Standard Size",
          "Occasion",
          "Laptop Size",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ],
        "price": 16560,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb341-2_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/J/T/JTMB341-2_7.jpg"
        ],
        "description": "Carry your laptop in style with this Western-inspired brown laptop briefcase from Justanned. This leather laptop briefcase offers versatility coupled with style with its multiple pockets, removable shoulder straps and durable webbing handle, making this bag easy to grip and an organizer's dream. With its zip-top opening and strong leather material, this briefcase offers accessibility and durability. ",
        "values": [
          "Carry your laptop in style with this Western-inspired brown laptop briefcase from Justanned. This leather laptop briefcase offers versatility coupled with style with its multiple pockets, removable shoulder straps and durable webbing handle, making this bag easy to grip and an organizer's dream. With its zip-top opening and strong leather material, this briefcase offers accessibility and durability.",
          "JTMB341-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Briefcase Bag",
          "Leather",
          "Dry Clean By Leather Specialist",
          "2",
          "Cotton",
          "6",
          "Bags",
          "Antique Brass",
          "JTMB341-2",
          "Standard",
          "Casual",
          "15",
          "Adult",
          "Zipper",
          "Fashion",
          "Brown",
          "11.43",
          "30.48"
        ],
        "discount": 75,
        "category2": "bags",
        "category3": "briefcase",
        "category1": "men",
        "inStock": true,
        "title": "BROWN MULTIPURPOSE BRIEFCASE BAG",
        "stock": 38,
        "productId": "0Xf9sRO6Wqh9PHtSCQo8"
      },
      {
        "description": "Swell up your accessory collection in a trendy way with this messenger bag from Justanned. With a solid pattern, it will impress you. This formal bag comes with an adjustable strap and has a front detail emboss branding on the flap. It is made of high-quality leather and cotton inner that lasts long. This brown messenger bag multiple compartments make it your ideal buy. ",
        "values": [
          "Swell up your accessory collection in a trendy way with this messenger bag from Justanned. With a solid pattern, it will impress you. This formal bag comes with an adjustable strap and has a front detail emboss branding on the flap. It is made of high-quality leather and cotton inner that lasts long. This brown messenger bag multiple compartments make it your ideal buy.",
          "JTMB458-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Messenger Bag",
          "MESSENGER BAG",
          "Goat Leather",
          "Dry Clean By Leather Specialist",
          "Polyester",
          "2",
          "Bags",
          "Gun Metal",
          "JTMB458-2",
          "Standard",
          "Casual",
          "2",
          "Adult",
          "Magnet Closure",
          "Fashion",
          "Brown",
          "33.02",
          "13",
          "27.94",
          "11"
        ],
        "discount": 75,
        "category2": "bags",
        "category3": "messenger",
        "category1": "men",
        "inStock": true,
        "title": "JUSTANNED MEN'S CLASSIC BROWN MESSENGER BAG",
        "stock": 34,
        "product_code": "SKU:JTMB458-2",
        "discounted_price": 2450,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Bags Type",
          "Concept",
          "Material/Fabric",
          "Material Care",
          "Lining Material",
          "No. of Pockets",
          "Type",
          "Zipper Info",
          "Style Code",
          "Standard Size",
          "Occasion",
          "No. of Zip",
          "Age Group",
          "Closure",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Width (In)",
          "Height (CM)",
          "Height (In)"
        ],
        "price": 9800,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_1_1.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_4.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_5.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmb458-2_7.jpg"
        ]
      }
    ],
    "belts": [
      {
        "productId": "1ifb5kWnAYY4e5XQMPeD",
        "product_code": "SKU:JTMBL022-3",
        "discounted_price": 563,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Belt Finishing",
          "Belt Thickness",
          "Belt Pattern",
          "Belt Holes",
          "Buckle Type",
          "Belt Width (MM)",
          "Buckle Material",
          "Material/Fabric",
          "Material Care",
          "Type",
          "Style Code",
          "Occasion",
          "Age Group",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ],
        "price": 2250,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl022-3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl022-3_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl022-3_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl022-3_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl022-3_4.jpg"
        ],
        "description": "From Justanned, this tan creased leather belt features a black pin buckle in a treated look and having a single keeper. Also available in big and tall sizes. ",
        "values": [
          "From Justanned, this tan creased leather belt features a black pin buckle in a treated look and having a single keeper. Also available in big and tall sizes.",
          "JTMBL022-3",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Matte",
          "3 MM",
          "Solid",
          "With Holes",
          "Pin-Hole Buckle",
          "38-40",
          "Antique Brass",
          "Leather",
          "Clean By Leather Specialist",
          "Belts",
          "JTMBL022-3",
          "Casual",
          "Adult",
          "Fashion",
          "Tan",
          "0.3",
          "3.8"
        ],
        "discount": 75,
        "category2": "belts",
        "category3": "casual",
        "category1": "men",
        "inStock": true,
        "title": "MEN'S TAN CREASED TREATED LEATHER BELT",
        "stock": 78
      },
      {
        "price": 2250,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl037-3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl037-3_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl037-3_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl037-3_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl037-3_6_1.jpg"
        ],
        "description": "An essential for a versatile wardrobe, this classic black belt from our men's range by Justanned is crafted from real leather with a single keeper and has a smart old silver pin buckle. ",
        "values": [
          "An essential for a versatile wardrobe, this classic black belt from our men's range by Justanned is crafted from real leather with a single keeper and has a smart old silver pin buckle.",
          "JTMBL037-3",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Matte",
          "3 MM",
          "Solid",
          "With Holes",
          "Pin-Hole Buckle",
          "38-40",
          "Old Silver",
          "Leather",
          "Clean By Leather Specialist",
          "Belts",
          "JTMBL037-3",
          "Casual",
          "Adult",
          "Fashion",
          "Tan",
          "0.3",
          "3.8"
        ],
        "discount": 75,
        "category2": "belts",
        "category3": "casual",
        "category1": "men",
        "inStock": true,
        "title": "ENGRAVED TAN MEN'S BELT",
        "stock": 83,
        "productId": "9C3imdU6rJ0FLG2nKgol",
        "product_code": "SKU:JTMBL037-3",
        "discounted_price": 563,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Belt Finishing",
          "Belt Thickness",
          "Belt Pattern",
          "Belt Holes",
          "Buckle Type",
          "Belt Width (MM)",
          "Buckle Material",
          "Material/Fabric",
          "Material Care",
          "Type",
          "Style Code",
          "Occasion",
          "Age Group",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ]
      },
      {
        "price": 2250,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl028-2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl028-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl028-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl028-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl028-2_4.jpg"
        ],
        "description": "An essential for any wardrobe, this men's classic pin buckle belt from Justanned is crafted from brown leather.. Ideal to wear with all jeans colour. ",
        "values": [
          "An essential for any wardrobe, this men's classic pin buckle belt from Justanned is crafted from brown leather.. Ideal to wear with all jeans colour.",
          "JTMBL028-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Matte",
          "3 MM",
          "Solid",
          "With Holes",
          "Pin-Hole Buckle",
          "38-40",
          "Old Silver",
          "Leather",
          "Clean By Leather Specialist",
          "Belts",
          "JTMBL028-2",
          "Casual",
          "Adult",
          "Fashion",
          "Brown",
          "0.3",
          "3.8"
        ],
        "discount": 75,
        "category2": "belts",
        "category3": "casual",
        "category1": "men",
        "inStock": true,
        "title": "ENGRAVED EDGE BROWN LEATHER BELT",
        "stock": 73,
        "productId": "AR7uayWlnHbSvkthsaP2",
        "product_code": "SKU:JTMBL028-2",
        "discounted_price": 563,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Belt Finishing",
          "Belt Thickness",
          "Belt Pattern",
          "Belt Holes",
          "Buckle Type",
          "Belt Width (MM)",
          "Buckle Material",
          "Material/Fabric",
          "Material Care",
          "Type",
          "Style Code",
          "Occasion",
          "Age Group",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ]
      },
      {
        "productId": "EoGxGY7Z5p5Mpekiwl7D",
        "product_code": "SKU:JTMBL029-2",
        "discounted_price": 563,
        "labels": [
          "Item Description",
          "SKU",
          "Disclaimer",
          "Belt Finishing",
          "Belt Thickness",
          "Belt Pattern",
          "Belt Holes",
          "Buckle Type",
          "Belt Width (MM)",
          "Buckle Material",
          "Material/Fabric",
          "Material Care",
          "Type",
          "Style Code",
          "Occasion",
          "Age Group",
          "Fashion Type",
          "Color",
          "Width (CM)",
          "Height (CM)"
        ],
        "price": 2250,
        "product_images": [
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl029-2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl029-2_6.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl029-2_2.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl029-2_3.jpg",
          "https://www.justanned.in/media/catalog/product/cache/1/image/17f82f742ffe127f42dca9de82fb58b1/j/t/jtmbl029-2_4.jpg"
        ],
        "description": "This brown leather belt from Justanned is made from leather with a two-tone textured finish and features a metal pin buckle fastening. Ideal to wear with all jeans colour. ",
        "values": [
          "This brown leather belt from Justanned is made from leather with a two-tone textured finish and features a metal pin buckle fastening. Ideal to wear with all jeans colour.",
          "JTMBL029-2",
          "This is a natural leather product, marking in the surface or color shading is to be accepted. These are inherent characteristics of real Leather & should NOT be considered as fault. The color may vary from product to product due to photographic lighting sources or differences in yours device screen settings.",
          "Matte",
          "3 MM",
          "Solid",
          "With Holes",
          "Pin-Hole Buckle",
          "38-40",
          "Antique Brass",
          "Leather",
          "Clean By Leather Specialist",
          "Belts",
          "JTMBL029-2",
          "Casual",
          "Adult",
          "Fashion",
          "Brown",
          "0.3",
          "3.8"
        ],
        "discount": 75,
        "category2": "belts",
        "category3": "casual",
        "category1": "men",
        "inStock": true,
        "title": "TWO-TONE LEATHER BELT",
        "stock": 14
      }
    ]
  }
}