
//User Reducer Types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'

//UI Reducer Types
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE'

//Data Reducer Types
export const SET_PRODUCT_HOME = 'SET_PRODUCT_HOME'
export const SET_CATEGORY_PRODUCT = 'SET_CATEGORY_PRODUCT'
export const SET_OVERVIEW_PRODUCT = 'SET_OVERVIEW_PRODUCT'
export const CLEAR_ARRAY = 'CLEAR_ARRAY'
export const RESET_UI = 'RESET_UI'

//Cart Reducer Type
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS'
export const HANDLE_ITEM_COUNT = 'HANDLE_ITEM_COUNT'

export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT'
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT'



